[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
sol_usd_oracle = "3EKbZCxvUXzrZaVKYHc7BcyqrVQPpMmN3vysSxPfZ6iE"
token_minter = "CuDJpGcDkPPUyFXQrGV6x3WZGADdiVE3tcK7WA4j5vFa"

[programs.localnet]
sol_usd_oracle = "3EKbZCxvUXzrZaVKYHc7BcyqrVQPpMmN3vysSxPfZ6iE"
token_minter = "CuDJpGcDkPPUyFXQrGV6x3WZGADdiVE3tcK7WA4j5vFa"

[registry]
url = "https://api.apr.dev"

[provider]
# cluster = "localnet"
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
litesvm = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""

[test.validator]
rpc_port = 9003
gossip_port = 9005
